# coding: utf-8

"""
    MANUFACTURING/18.100.001

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.file_link import FileLink  # noqa: E501
from swagger_client.rest import ApiException


class TestFileLink(unittest.TestCase):
    """FileLink unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFileLink(self):
        """Test FileLink"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.file_link.FileLink()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
