# coding: utf-8

"""
    MANUFACTURING/18.100.001

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.labor_entry_detail_allocation import LaborEntryDetailAllocation  # noqa: E501
from swagger_client.rest import ApiException


class TestLaborEntryDetailAllocation(unittest.TestCase):
    """LaborEntryDetailAllocation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLaborEntryDetailAllocation(self):
        """Test LaborEntryDetailAllocation"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.labor_entry_detail_allocation.LaborEntryDetailAllocation()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
