# coding: utf-8

"""
    MANUFACTURING/18.100.001

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.http_error import HttpError  # noqa: E501
from swagger_client.rest import ApiException


class TestHttpError(unittest.TestCase):
    """HttpError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHttpError(self):
        """Test HttpError"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.http_error.HttpError()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
