# coding: utf-8

"""
    MANUFACTURING/18.100.001

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.labor_entry_api import LaborEntryApi  # noqa: E501
from swagger_client.rest import ApiException


class TestLaborEntryApi(unittest.TestCase):
    """LaborEntryApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.labor_entry_api.LaborEntryApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_labor_entry_delete_by_id(self):
        """Test case for labor_entry_delete_by_id

        Deletes the record by its session identifier.  # noqa: E501
        """
        pass

    def test_labor_entry_get_ad_hoc_schema(self):
        """Test case for labor_entry_get_ad_hoc_schema

        Retrieves the schema of custom fields of the entity from the system.  # noqa: E501
        """
        pass

    def test_labor_entry_get_by_id(self):
        """Test case for labor_entry_get_by_id

        Retrieves a record by the value of the session entity ID from the system.  # noqa: E501
        """
        pass

    def test_labor_entry_get_list(self):
        """Test case for labor_entry_get_list

        Retrieves records that satisfy the specified conditions from the system.  # noqa: E501
        """
        pass

    def test_labor_entry_put_entity(self):
        """Test case for labor_entry_put_entity

        Creates a record or updates an existing record.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
