# coding: utf-8

"""
    MANUFACTURING/18.100.001

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.boolean_value import BooleanValue  # noqa: E501
from swagger_client.rest import ApiException


class TestBooleanValue(unittest.TestCase):
    """BooleanValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBooleanValue(self):
        """Test BooleanValue"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.boolean_value.BooleanValue()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
