# coding: utf-8

"""
    MANUFACTURING/18.100.001

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class Entity(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'row_number': 'int',
        'note': 'str',
        'custom': 'dict(str, dict(str, CustomField))',
        'files': 'list[FileLink]'
    }

    attribute_map = {
        'id': 'id',
        'row_number': 'rowNumber',
        'note': 'note',
        'custom': 'custom',
        'files': 'files'
    }

    def __init__(self, id=None, row_number=None, note=None, custom=None, files=None, _configuration=None):  # noqa: E501
        """Entity - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._id = None
        self._row_number = None
        self._note = None
        self._custom = None
        self._files = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if row_number is not None:
            self.row_number = row_number
        if note is not None:
            self.note = note
        if custom is not None:
            self.custom = custom
        if files is not None:
            self.files = files

    @property
    def id(self):
        """Gets the id of this Entity.  # noqa: E501


        :return: The id of this Entity.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Entity.


        :param id: The id of this Entity.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def row_number(self):
        """Gets the row_number of this Entity.  # noqa: E501


        :return: The row_number of this Entity.  # noqa: E501
        :rtype: int
        """
        return self._row_number

    @row_number.setter
    def row_number(self, row_number):
        """Sets the row_number of this Entity.


        :param row_number: The row_number of this Entity.  # noqa: E501
        :type: int
        """

        self._row_number = row_number

    @property
    def note(self):
        """Gets the note of this Entity.  # noqa: E501


        :return: The note of this Entity.  # noqa: E501
        :rtype: str
        """
        return self._note

    @note.setter
    def note(self, note):
        """Sets the note of this Entity.


        :param note: The note of this Entity.  # noqa: E501
        :type: str
        """

        self._note = note

    @property
    def custom(self):
        """Gets the custom of this Entity.  # noqa: E501


        :return: The custom of this Entity.  # noqa: E501
        :rtype: dict(str, dict(str, CustomField))
        """
        return self._custom

    @custom.setter
    def custom(self, custom):
        """Sets the custom of this Entity.


        :param custom: The custom of this Entity.  # noqa: E501
        :type: dict(str, dict(str, CustomField))
        """

        self._custom = custom

    @property
    def files(self):
        """Gets the files of this Entity.  # noqa: E501


        :return: The files of this Entity.  # noqa: E501
        :rtype: list[FileLink]
        """
        return self._files

    @files.setter
    def files(self, files):
        """Sets the files of this Entity.


        :param files: The files of this Entity.  # noqa: E501
        :type: list[FileLink]
        """

        self._files = files

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Entity, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Entity):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Entity):
            return True

        return self.to_dict() != other.to_dict()
